project_id = "wihyiqyptkxrwrwwnuzn"

[auth]
site_url = "http://localhost:8080"
additional_redirect_urls = ["http://localhost:8080", "http://localhost:8080/auth", "http://127.0.0.1:8080", "http://127.0.0.1:8080/auth"]

[auth.email]
enable_signup = true
enable_confirmations = true
double_confirm_changes = true
secure_password_change = false
